### PR TITLE
Also apply sync_opts to sync_releases

### PR DESCRIPTION
**Pull request by ejpcmac**
The `sync_opts` configuration options allows to set things like `timeout: :infinity`, which can be interesting when syncing on a low-bandwidth connection. However, it was previously applied to `sync_created_packages` and `sync_deleted_packages`, but not to `sync_releases`. This PR aims to fix that.

### CODE REVIEW

**Comment by wojtekmach** [comment]
Thank you!

And good luck on your trip!

**Comment by ejpcmac** [comment]
Thanks! 10 days left before I am on the boat. My Hex mirror is now fully operational, so it’s all good :)

**Comment by wojtekmach** [comment]
Oh, just remembered that a friend of mine recently created an utility that allows you to easily sync Hex docs (and GitHub repos) so that may come in handy unless you already have a backup of these too :) See: https://github.com/JamesLavin/sync_repos. cc @JamesLavin

**Comment by ejpcmac** [comment]
> Oh, just remembered that a friend of mine recently created an utility that allows you to easily sync Hex docs (and GitHub repos) so that may come in handy unless you already have a backup of these too :) See: https://github.com/JamesLavin/sync_repos. cc @JamesLavin

Oh, that’s a neat tool! I’m not fond of automatically pulling / pushing Git repos, I’m more a `git fetch` kind of guy, just to keep the repo in sync but handling the working copy by hand. The Hex docs part is very interesting though. I used to have Dash on my Mac, but now Zeal on Linux does not (yet) handle the docs from Hex.

**Comment by JamesLavin** [comment]
Thanks for your super-helpful comment, @ejpcmac!

I'll add a `fetch-master` option and let the user choose that and/or `pull-rebase` (since they're totally unrelated actions unless `master` is checked out).

--James

**Pull request merged**
