### PR TITLE
Add `:sync_opts` option to MiniRepo.Mirror

### PR DESCRIPTION
**Pull request by alesasnouski**

### CODE REVIEW

**Comment by wojtekmach** [comment]
I think this is a good addition, since syncing is IO bound, having some knobs to turn seems useful.

Given we always use `ordered: false`, instead of having to set it every time we could do `Keyword.merge([ordered: false], opts)` (and need to document that we are merging)

Instead of having `package_sync_opts` and `release_sync_opts` we could start with a single config key: `sync_opts` to keep it simple. Currently we spawn release sync from package sync so we have M*N tasks but I wanted to change that in the future anyway so we always have N tasks.

What do you think?

**Comment by alesasnouski** [comment]
Sure, updated :)

**Comment by alesasnouski** [comment]
Could you please review / comment / merge my PR ?

**Comment by wojtekmach** [comment]
I’m out on vacation, will review next week!

**Comment by wojtekmach** [comment]
Thank you!

**Pull request merged**
